In [1]:
import numpy as np

In [2]:
new_array1=np.ones(4)

In [4]:
new_array1

array([1., 1., 1., 1.])

In [9]:
new_array2=np.array([5,6,7,8])
new_array3=np.array([1,2,3,4])
new_array2[-1]

8

In [10]:
new_array3 + new_array2

array([ 6,  8, 10, 12])

In [12]:
new_array3.sum()

10

In [13]:
new_array3.mean()

2.5

In [17]:
# multi dimentional array
x=np.array([[10,20,30],[40,50,60]])
y=np.ones((3,4))

In [18]:
x

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
x.sum()

210

In [20]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
z=np.random.random((3,3,2))

In [37]:
z

array([[[0.83465769, 0.18950199],
        [0.40273173, 0.64083007],
        [0.00387047, 0.13507211]],

       [[0.09602463, 0.43511878],
        [0.7357014 , 0.99688175],
        [0.40794178, 0.76960904]],

       [[0.52549832, 0.2271827 ],
        [0.34580506, 0.59230337],
        [0.82413644, 0.62365773]]])

In [26]:
a1=np.array([[5,6],[7,8]])

In [27]:
a2=np.array([[2,3],[4,5]])

In [28]:
a1+a2

array([[ 7,  9],
       [11, 13]])

In [29]:
a1.dot(a2)

array([[34, 45],
       [46, 61]])

In [33]:
z.dot(a2)

array([[[3.02642564, 4.16767908],
        [2.67250118, 3.60640359],
        [3.13000463, 4.32063661]],

       [[2.46568167, 3.32357163],
        [3.3611571 , 4.70080511],
        [4.23168197, 5.51315433]],

       [[3.52436082, 4.54781897],
        [1.18327871, 1.63441411],
        [3.7712703 , 5.04144573]]])

In [38]:
a1.max()

8

In [43]:
z[0:3,1]

array([[0.40273173, 0.64083007],
       [0.7357014 , 0.99688175],
       [0.34580506, 0.59230337]])

In [6]:
num1=np.arange(15)

In [7]:
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])